version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    env_file:
        secret.env
    volumes:
      - mongo-db-auth:/data/db
    networks:
      - mongo_auth_db
      - mongo_auth_adapter
      - mongo_auth_gui

  mongo-express:
    depends_on:
      - mongo
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file:
        secret.env      
    networks:
      - mongo_auth_db

  auth_server:
      depends_on:
        - mongo
      image: auth_server
      ports:
        - 5000:5000
      restart: always
      build: ./auth
      env_file:
        secret.env
      networks:
        - mongo_auth_adapter

volumes:
  mongo-db-auth:
  gui:

networks:
  mongo_auth_db:
    name: mongo_auth_db
  mongo_auth_adapter:
    name: mongo_auth_adapter
  mongo_auth_gui:
    name: mongo_auth_gui
